version: '3'
services:
  mqtt:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo/
    ports:
      - 1883:1883

  mongo:
    image: mongo:3.6
    restart: unless-stopped
    command: mongod --smallfiles

  redis:
    image: redis:latest
    restart: unless-stopped

